### PR TITLE
Implement Animation Map format

### PR DESCRIPTION
**Pull request by MishaProductions**
This PR adds support for the AMAP format. Based on the information from: [this link](https://winclassic.net/thread/1825/research-dwm-animations-uxtheme-amap). I also updated the project to .NET framework 4.6 as you can't download the targeting pack for .NET framework 4.5.
image

### CODE REVIEW

**Comment by nptr** [comment]
Very nice! Thanks! I'll build and test it. 
Might take some days since I have to setup a windows machine again :)

**Comment by nptr** [comment]
Changes look good to me. I did a bit of refactoring to bring it in-line with the rest of the application. Mainly moving things around.
I'd push those changes to your branch if you don't mind. I can also hold on to them if you want to make more additions!

**Comment by MishaProductions** [comment]
I will open another PR to add support for adding/removing states/parts.

**Comment by nptr** [comment]
Shall I rebase my changes onto your PR and merge then?

**Comment by MishaProductions** [comment]
Sure!

**Comment by nptr** [comment]
Changes done & pushed to your branch.
- Formatting
- `ContainsKey() `+` operator[]` => `TryGetValue()`.
- Not loading AMAP when <= W8: There is no AMAP.
- Moved animation & timing function maps to a separate file
- Added a unit test: binary compare new (unchanged) AMAP to the original

I'll do a bit more testing and experimentation tomorrow and then go from there.

**Comment by nptr** [comment]
Alright, changes are in, thanks gain! :) 

_(You'll have to point your local master back at mine or at my development branch if you have some more things to commit, because i did some rebasing.)_

**Pull request merged**
